### ISSUE TITLE
CGO option no longer whitelisted

### ISSUE THREAD

**Issue by jazzyeagle** [cheggaaa/go-poppler#5]
Per https://github.com/golang/go/issues/23749#issuecomment-387018887, cflags-only-I is no longer a whitelisted cgo option for the Go compiler, hence I was not able to build using go get.  I set the environment variable as indicated as a temporary fix, but I'm not familiar enough with the flags and how you're using them to propose a permanent fix.  If you could look into it for future users of your library, I'm sure folks would appreciate that.  Thanks!

**Comment by cheggaaa** [comment]
I pushed some fixes. Please check the last version.
