### ISSUE TITLE
Software license?

### ISSUE THREAD

**Issue by kindrowboat** [cheggaaa/go-poppler#9]
I would like to use go-poppler in one of my projects, but it doesn't have a license. Might I suggest the MIT license?

Lack of a license, also prevents pkg.go.dev from displaying the package documentation [as seen here](https://pkg.go.dev/github.com/cheggaaa/go-poppler@v0.0.0-20200501084356-29faf5e9657d?tab=doc).

**Comment by bovepm** [comment]
Doesn't using poppler (GPL license) imply to use GPL license instead of MIT?
Source: https://www.gnu.org/licenses/gpl-faq.en.html#IfLibraryIsGPL

**Comment by kindrowboat** [comment]
Ah, yes you're right. I didn't know that poppler was under GPL.

https://gitlab.freedesktop.org/poppler/poppler/-/blob/master/COPYING
